# Generated by Django 2.0.9 on 2018-12-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('synopsis', models.TextField()),
                ('published_year', models.CharField(max_length=4)),
                ('book_cover', models.ImageField(default='media/none/no-img.jpg', upload_to='media/')),
            ],
        ),
    ]
