# Generated by Django 2.0.9 on 2018-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_post_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_cover',
            field=models.ImageField(default='/none/no-img.jpg', upload_to='image'),
        ),
    ]
