# Generated by Django 2.0.9 on 2018-12-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
