# Generated by Django 2.0.9 on 2019-01-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_comment_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isbn_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.CharField(default='', max_length=300),
        ),
    ]
